server:
 port: 8080
spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#配置mybatis相关，包括别名和mapper位置
mybatis:
  type-aliases-package: com.xcc.pojo
  #这里mapper.xml是放在resource/mybatis/mapper中
  mapper-locations: classpath:mybatis/mapper/*.xml
